In [1]:
import torch

In [2]:
x = torch.zeros(3,3)

In [3]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
x = torch.rand(4,3)

In [5]:
print(x)

tensor([[0.3626, 0.2341, 0.6524],
        [0.4106, 0.5851, 0.1434],
        [0.2815, 0.8149, 0.2281],
        [0.1827, 0.4511, 0.8528]])


In [6]:
x.size()

torch.Size([4, 3])

In [7]:
y = torch.rand(4,3)

In [8]:
print(x+y)

tensor([[1.1168, 0.9608, 1.0173],
        [0.4482, 1.2128, 0.2367],
        [0.5343, 0.9282, 0.4945],
        [0.4028, 0.5796, 1.5417]])


In [9]:
z = x.numpy()

In [10]:
type(z)

numpy.ndarray